- hosts: localhost
  vars:
    Name: ""
    ImageName: ""
    imageTag: ""
  #remote_user: ansible
  #become: true
  gather_facts: no
  connection: local
  tasks:
    - name: Deploy app
      command: "/usr/local/bin/helm install --name={{ Name }}  ./helm --set image.repository={{ ImageName }} --set name={{ Name }} --set image.tag={{ imageTag }}"
      delegate_to: localhost
      ignore_errors: yes
    - name: Update app
      command: "/usr/local/bin/helm upgrade --recreate-pods --set image.repository={{ ImageName }} --set image.tag={{ imageTag }} --set name={{ Name }} {{ Name }} ./helm"
      delegate_to: localhost
      ignore_errors: yes
    - name: Deploy apache configuration
      command: "cp prod.conf /etc/apache2/sites-available/prod-{{ Name }}.conf"
      delegate_to: localhost
      ignore_errors: no
    - name: Replace custom variables
      command: "sed -i "s/${-- Name --}/${{{ Name }}}/g" /etc/apache2/sites-available/prod-{{ Name }}.conf"
      delegate_to: localhost
      ignore_errors: no
    - name: Enable configuration
      command: "sudo a2ensite prod-{{ Name }}"
      delegate_to: localhost
      ignore_errors: no
    - name: Reload apache configurations
      command: "sudo service apache2 reload"
      delegate_to: localhost
      ignore_errors: no
